### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by Fengxiaoxx** [stevenreich47/ensemble-distillation-structured-prediction#1]
When I used 'PIP install --editable./' to install the tool, the system reported the following error. How can I resolve this error
![erro](https://user-images.githubusercontent.com/43958531/98535611-5e3caf80-22c1-11eb-8d62-910dfdc4ef53.png)
?

**Comment by noa** [comment]
@Fengxiaoxx You may have better luck with something like:

```
python setup.py develop --user
```

**Comment by Fengxiaoxx** [comment]
> @Fengxiaoxx You may have better luck with something like:
> 
> ```
> python setup.py develop --user
> ```
My problem has been solved. Thank you very much!
